#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "\033[1;31m⚠️  You can't commit directly to the main branch! ⚠️ \033[0m"

	echo "(blocking from '.husky/pre-commit')"
  exit 1
fi

# Check for files in ./kysely/migrations in the commit
if git diff --cached --name-only | grep -q "^kysely/migrations/"; then
  echo "\033[1;33m⚠️  It seems a migration file was affected by this commit! Please ensure proper procedures around migrations are followed ⚠️\033[0m"

  sh ./utils/scripts/print-introspect-message.sh
fi

pnpm exec lint-staged
